### ISSUE TITLE
schubert-winterreise expresses bass as notes instead of deegree

### ISSUE THREAD

**Issue by n28div** [smashub/choco#87]
See `partitions/schubert-winterreise/raw/ann_score_chord/Schubert_D911-01.csv:3` for instance, where *C#:dim7/D* is used instead of *C#:dim7/b2*

**Comment by andreamust** [comment]
In https://github.com/smashub/choco/commit/079df978011835aa7fcfc873d01e51512f9dc971 a fix has been added and converted file generated.
New files will be added to the current release.
