### ISSUE TITLE
real-book uses 's' as modifier instead of '#'

### ISSUE THREAD

**Issue by n28div** [smashub/choco#88]
see for instance `partitions/real-book/raw/'round Midnight - Thelonious Monk.Mgu.xlab : 3`, *Bb:7(s5,\*5,s9)* is used instead of *Bb:7(#&#8203;5,\*5,#&#8203;9)* according to standard Harte notation.

**Comment by andreamust** [comment]
In https://github.com/smashub/choco/commit/dcc18c23428d72ff45092ae8881055b10aead7de a temporary fix has been added to the real-book partition and files regenerated.
Updated files will be added to current release.
