### ISSUE TITLE
typos on robbie-williams partition

### ISSUE THREAD

**Issue by n28div** [smashub/choco#89]
Two files on the robbie-williams partition, `robbie-williams/choco/jams/robbie-williams_40.jams` and `robbie-williams/choco/jams/robbie-williams_57.jams`, contains typos on single chords (respectively *Bb:7/3* as *Bb7/3* and *Bb:7/5* as *Bb7/5*)

**Comment by andreamust** [comment]
In https://github.com/smashub/choco/commit/0643c50b30cb92bc22bf0409782af1fcc1fc913b a fix has been added to the converter and new files have been generated.
Updated files will be added to the current release.
