### ISSUE TITLE
rock-corpus metric parsed as chord root

### ISSUE THREAD

**Issue by n28div** [smashub/choco#91]
According to http://rockcorpus.midside.com/harmonic_analyses.html, section D - Special Symbols, '*... the symbol [0], which refers to a span of music without any clear meter ...'*.

`[0]` is wrongly parsed as the root of the chord instead. See `rock-corpus/choco/jams-converted/rock-corpus_132.jams` where *0:I* is parsed instead of *E:I*.

**Comment by jonnybluesman** [comment]
Thanks for spotting this. The no-metre symbol is no longer interpreted as a key. Waiting for other changes to be made on the rock-corpus before regenerating the JAMS files.
